### ISSUE TITLE
Compat strings

### ISSUE THREAD

**Issue by andrewbaxter** [libre-computer-project/libretech-wiring-tool#16]
I'm fairly new to device-tree so please forgive me if I'm missing something simple...

I have a Le Potato v1, and on boot `/proc/device-tree/compat` shows (roughly) `libretech,aml-s905x-cc` `amlogic,s905x` `amlogic,meson-gxl`.  I don't know what this is, but I see it here too: https://boot.libre.computer/ci/aml-s905x-cc.dts and in the Linux kernel source: https://github.com/torvalds/linux/blob/46c6d2b186915176be5acc5d4b6f9793eb32a0c7/arch/arm64/boot/dts/amlogic/meson-gxl-s905x-libretech-cc.dts

All the files in the `aml-s905x-cc` directory here use the compat string `libretech,cc` instead of `libretech,aml-s905x-cc`.  I'm having trouble getting them to apply correctly because of that.

Should they be `libretech,aml-s905x-cc` instead?

**Comment by dsx724** [comment]
You are correct. They should be `libretech,aml-s905x-cc`. The overlays are matching the second compats. We have updated the overlays.

**Comment by andrewbaxter** [comment]
Oh awesome! Thanks so much!

For reference, fixed here https://github.com/libre-computer-project/libretech-wiring-tool/commit/8a8ebff223e8a8baceb787291d30376d42f39693

**Comment by dsx724** [comment]
Thank you for reporting this!
